## Day01 20 July 2020

### IDLE, VS Code, Spyder, Atom, Py Charm, Jupyter Notebooks......

Numpy, Pandas, Matpotlib



## Python List


Non Homogenous group of data type of elements

In [1]:
[1, 4, 5, 'asaD', 'SDFSD', 12.2]

[1, 4, 5, 'asaD', 'SDFSD', 12.2]

In [ ]:
numbers --> int, float, complex

1000000 --> int, float, complex

In [2]:
import numpy

In [3]:
arr = numpy.array()

TypeError: array() missing required argument 'object' (pos 1)

In [4]:
arr = numpy.array([])
arr1 = numpy.array(())

print(arr, type(arr))

[] <class 'numpy.ndarray'>


In [5]:
import numpy as np

In [7]:
print(np.array([1, 2, 3]))

[1 2 3]


In [8]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [9]:
arr.dtype

dtype('int32')

In [13]:
arr = np.array([])
print(arr)

arr = np.append(arr, [12, 14])

print(arr)

[]
[12. 14.]


In [14]:
print(arr)

[12. 14.]


range(start, stop, inc/dec)

start = 0
stop = req argument exclusive
inc/dec = 1

In [17]:
print(np.arange(10))
print(np.arange(1, 10))
print(np.arange(1,50,10))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 1 11 21 31 41]


In [18]:
arr = np.arange(1, 10)

In [20]:
arr.size, len(arr)

(9, 9)

In [21]:
arr.itemsize

4

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr.nbytes

36

In [28]:
zeros = np.zeros(10, dtype = "int8")
print(zeros, zeros.dtype)

[0 0 0 0 0 0 0 0 0 0] int8


In [29]:
zeros.nbytes

10

In [31]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
np.full(10, "APSSDC")

array(['APSSDC', 'APSSDC', 'APSSDC', 'APSSDC', 'APSSDC', 'APSSDC',
       'APSSDC', 'APSSDC', 'APSSDC', 'APSSDC'], dtype='<U6')

In [35]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
np.arange(1.0, 11.0, 0.18367347)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306123,
        2.8367347 ,  3.02040817,  3.20408164,  3.38775511,  3.57142858,
        3.75510205,  3.93877552,  4.12244899,  4.30612246,  4.48979593,
        4.6734694 ,  4.85714287,  5.04081634,  5.22448981,  5.40816328,
        5.59183675,  5.77551022,  5.95918369,  6.14285716,  6.32653063,
        6.5102041 ,  6.69387757,  6.87755104,  7.06122451,  7.24489798,
        7.42857145,  7.61224492,  7.79591839,  7.97959186,  8.16326533,
        8.3469388 ,  8.53061227,  8.71428574,  8.89795921,  9.08163268,
        9.26530615,  9.44897962,  9.63265309,  9.81632656, 10.00000003,
       10.1836735 , 10.36734697, 10.55102044, 10.73469391, 10.91836738])